# Generated by Django 6.0 on 2026-05-03 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_updated_at'),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasting_alerts', to='accounts.restaurant'),
        ),
    ]
