# Generated by Django 6.0 on 2026-02-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('VOID', 'Void'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10),
        ),
    ]
