# Generated by Django 6.0 on 2026-02-22 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_updated_at'),
        ('sales', '0002_alter_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='import_ref',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['restaurant', 'sold_at'], name='sales_sale_restaur_e789bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('import_ref__isnull', False), models.Q(('import_ref', ''), _negated=True)), fields=('restaurant', 'import_ref'), name='uniq_sale_import_ref_per_restaurant'),
        ),
    ]
