# Generated by Django 6.0 on 2026-02-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_updated_at'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(max_length=60),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'sku'), name='uniq_inventory_sku_per_restaurant'),
        ),
    ]
