# Generated by Django 6.0 on 2026-03-08 07:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_buffer_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='buffer_size',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
