# Generated by Django 6.0 on 2026-02-22 16:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_restaurant_updated_at'),
        ('inventory', '0002_alter_inventoryitem_sku_and_more'),
        ('menu', '0002_alter_category_name_alter_category_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('source_plan_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_purchase_requests_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_purchase_requests', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'kitchen_purchaserequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenPurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('suggested_purchase_qty', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reason', models.CharField(blank=True, default='LOW_STOCK', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_purchase_request_lines', to='inventory.inventoryitem')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kitchen.kitchenpurchaserequest')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_purchase_request_lines', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'kitchen_purchaserequestline',
                'ordering': ['item__name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('suggested_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('suggestion_basis', models.CharField(blank=True, default='', max_length=120)),
                ('planned_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('prepared_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, default='')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_productions', to='menu.menuitem')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_productions', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'kitchen_menuitemproduction',
                'ordering': ['-date', 'menu_item_id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('waste_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reason', models.CharField(blank=True, choices=[('UNSOLD', 'Unsold'), ('BURNT', 'Burnt'), ('RETURNED', 'Returned'), ('EXPIRED', 'Expired')], default='', max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_wastes', to='menu.menuitem')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_wastes', to='accounts.restaurant')),
            ],
            options={
                'db_table': 'kitchen_menuitemwaste',
                'ordering': ['-date', 'menu_item_id'],
            },
        ),
        migrations.AddIndex(
            model_name='kitchenpurchaserequest',
            index=models.Index(fields=['restaurant', 'request_date'], name='idx_kpr_rest_req_date'),
        ),
        migrations.AddIndex(
            model_name='kitchenpurchaserequest',
            index=models.Index(fields=['restaurant', 'status'], name='idx_kpr_rest_status'),
        ),
        migrations.AddIndex(
            model_name='kitchenpurchaserequestline',
            index=models.Index(fields=['restaurant', 'item'], name='idx_kprl_rest_item'),
        ),
        migrations.AddIndex(
            model_name='kitchenpurchaserequestline',
            index=models.Index(fields=['purchase_request'], name='idx_kprl_req'),
        ),
        migrations.AddIndex(
            model_name='menuitemproduction',
            index=models.Index(fields=['restaurant', 'date'], name='idx_kitchen_prod_rest_date'),
        ),
        migrations.AddIndex(
            model_name='menuitemproduction',
            index=models.Index(fields=['restaurant', 'menu_item'], name='idx_kitchen_prod_rest_menu'),
        ),
        migrations.AddConstraint(
            model_name='menuitemproduction',
            constraint=models.UniqueConstraint(fields=('restaurant', 'date', 'menu_item'), name='uniq_kitchen_prod_rest_date_menu'),
        ),
        migrations.AddIndex(
            model_name='menuitemwaste',
            index=models.Index(fields=['restaurant', 'date'], name='idx_kitchen_waste_rest_date'),
        ),
        migrations.AddIndex(
            model_name='menuitemwaste',
            index=models.Index(fields=['restaurant', 'menu_item'], name='idx_kitchen_waste_rest_menu'),
        ),
        migrations.AddConstraint(
            model_name='menuitemwaste',
            constraint=models.UniqueConstraint(fields=('restaurant', 'date', 'menu_item'), name='uniq_kitchen_waste_rest_date_menu'),
        ),
    ]
