# Generated by Django 6.0 on 2026-03-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REQUEST', 'Request'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='REQUEST', max_length=10),
        ),
    ]
